spring:
  r2dbc:
    username: root
    password: admin
    url: r2dbc:mysql://localhost:3306/adviser?serverTimezone=CST
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
      max-idle-time: 30m
  jpa:
    open-in-view: false
  liquibase:
    url: jdbc:mysql://localhost:3306/adviser?serverTimezone=CST
    user: root
    password: admin

app:
  integration:
    alphavantage:
      enabled: true
      url: https://www.alphavantage.co/
      apiKey: 86T2JAZAYN5Q24FS