spring:
  r2dbc:
    username: root
    password: admin
    url: r2dbc:mysql://localhost:3306/adviser?serverTimezone=America/Chicago
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
      max-idle-time: 30m
  jpa:
    open-in-view: false
  liquibase:
    url: jdbc:mysql://localhost:3306/adviser?serverTimezone=America/Chicago
    user: root
    password: admin

app:
  integration:
    alphavantage:
      enabled: true
      url: https://www.alphavantage.co/
      apiKeys:
        - 86T2JAZAYN5Q24FS
        - SWFMVR675KNRWHWZ
        - X6SWSXRN0FX65RIA

rating:
  eligibility:
    market-cap:
      enabled: true
      threshold: 1_000_000_000
    enterprise-value:
      enabled: true
      threshold: 1_000_000_000
    earnings:
      enabled: true
      threshold: 0